jobs:
  - name: development
    max_in_flight: 1
    plan:
      - get: meta
        resource: meta-development
      - get: dataworks-hbase-import
        trigger: true
      - get: dataworks-behavioural-framework
        trigger: false
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: default
          TF_VAR_source_hbase_snapshot_workspace: 'default'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: default
          TF_VAR_source_hbase_snapshot_workspace: 'default'
      - .: (( inject meta.plan.e2e-tests))
        params:
          TF_WORKSPACE: development
          AWS_ACC: ((aws_account.development))
          AWS_ROLE_ARN: arn:aws:iam::((aws_account.development)):role/ci