jobs:
  - name: pull-request
    plan:
      - get: dataworks-hbase-import-pr
        resource: dataworks-hbase-import-pr
        trigger: true
        version: every
      - put: dataworks-hbase-import-pr
        params:
          path: dataworks-hbase-import-pr
          status: pending
      - .: (( inject meta.plan.terraform-bootstrap ))
        input_mapping:
          dataworks-hbase-export: dataworks-hbase-import-pr
      - .: (( inject meta.plan.terraform-plan ))
        input_mapping:
          dataworks-hbase-export: dataworks-hbase-import-pr
        params:
          TF_WORKSPACE: "qa"
          DETAILED_EXITCODE: ""
        on_failure:
          put: dataworks-hbase-import-pr
          params:
            path: dataworks-hbase-import-pr
            status: failure
        on_success:
          put: dataworks-hbase-import-pr
          params:
            path: dataworks-hbase-import-pr
            status: success
